### ISSUE TITLE
Does not support standalone test targets

### ISSUE THREAD

**Issue by NReilingh** [bitrise-steplib/steps-xcode-test-mac#16]
I am building a swift CLI app, which means the main target cannot have tests directly associated. (See https://forums.developer.apple.com/thread/52211).

The workaround described by Apple Staff in that thread for this is to define a second target and scheme to only use for testing. This step breaks on this type of scheme because it attempts to run the "build" action, which causes the error "The scheme 'MyTestScheme' is not configured for running."

**Comment by Roland-Bak** [comment]
Thanks @NReilingh , we'll take a look! 🙂

**Comment by coredumped** [comment]
I'm in the same boat, are there any workarounds?

**Comment by NReilingh** [comment]
@coredumped I'm pretty far away from this project at this point, but someone on staff just added a comment to the PR: https://github.com/bitrise-steplib/steps-xcode-test-mac/pull/17

**Comment by istvankovacs-bitrise** [comment]
Hi @coredumped, please make sure that the `Run` target is checked for the test scheme, as the error message suggests, or alternatively, you could run the main scheme, instead of the test scheme, since there the `Run` action is checked by default.

**Comment by adborbas** [comment]
Hi,

I will be closing the issue due to inactivity. Please feel free to open a new one incase you still have any concerns. Thanks
